"""snapshot every product (including attachments) so server matches local

Generated by scripts/snapshot_products.py. UPSERTs the accompanying
``0009_products_snapshot.json`` file into the products table — see migration 0007
for the rationale and operational notes.

Revision ID: 0009_products_snapshot
Revises: 0008_add_proposal_agent_product
Create Date: 2026-05-12
"""
import json
import pathlib
from typing import Sequence, Union

from alembic import op
from sqlalchemy.sql import text

revision: str = "0009_products_snapshot"
down_revision: Union[str, None] = "0008_add_proposal_agent_product"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


DATA_FILE = pathlib.Path(__file__).parent / "0009_products_snapshot.json"


_UPSERT_SQL = text(
    """
    INSERT INTO products (
        id, slug, icon_name, url, video_url, screenshots,
        is_visible, sort_order,
        title_en, title_ar,
        description_en, description_ar,
        problem_en, problem_ar,
        solution_en, solution_ar,
        phases_en, phases_ar,
        deliverables_en, deliverables_ar,
        ppt_filename, ppt_data, industries,
        created_at, updated_at
    )
    VALUES (
        gen_random_uuid(), :slug, :icon_name, :url, :video_url,
        CAST(:screenshots AS jsonb),
        :is_visible, :sort_order,
        :title_en, :title_ar,
        :description_en, :description_ar,
        :problem_en, :problem_ar,
        :solution_en, :solution_ar,
        CAST(:phases_en AS jsonb), CAST(:phases_ar AS jsonb),
        CAST(:deliverables_en AS jsonb), CAST(:deliverables_ar AS jsonb),
        :ppt_filename, :ppt_data, CAST(:industries AS jsonb),
        NOW(), NOW()
    )
    ON CONFLICT (slug) DO UPDATE SET
        icon_name       = EXCLUDED.icon_name,
        url             = EXCLUDED.url,
        video_url       = EXCLUDED.video_url,
        screenshots     = EXCLUDED.screenshots,
        is_visible      = EXCLUDED.is_visible,
        sort_order      = EXCLUDED.sort_order,
        title_en        = EXCLUDED.title_en,
        title_ar        = EXCLUDED.title_ar,
        description_en  = EXCLUDED.description_en,
        description_ar  = EXCLUDED.description_ar,
        problem_en      = EXCLUDED.problem_en,
        problem_ar      = EXCLUDED.problem_ar,
        solution_en     = EXCLUDED.solution_en,
        solution_ar     = EXCLUDED.solution_ar,
        phases_en       = EXCLUDED.phases_en,
        phases_ar       = EXCLUDED.phases_ar,
        deliverables_en = EXCLUDED.deliverables_en,
        deliverables_ar = EXCLUDED.deliverables_ar,
        ppt_filename    = EXCLUDED.ppt_filename,
        ppt_data        = EXCLUDED.ppt_data,
        industries      = EXCLUDED.industries,
        updated_at      = NOW()
    """
)


def upgrade() -> None:
    with open(DATA_FILE, encoding="utf-8") as f:
        products = json.load(f)

    conn = op.get_bind()
    for p in products:
        conn.execute(
            _UPSERT_SQL,
            {
                "slug":            p["slug"],
                "icon_name":       p["icon_name"],
                "url":             p["url"],
                "video_url":       p["video_url"],
                "screenshots":     json.dumps(p["screenshots"]),
                "is_visible":      p["is_visible"],
                "sort_order":      p["sort_order"],
                "title_en":        p["title_en"],
                "title_ar":        p["title_ar"],
                "description_en":  p["description_en"],
                "description_ar":  p["description_ar"],
                "problem_en":      p["problem_en"],
                "problem_ar":      p["problem_ar"],
                "solution_en":     p["solution_en"],
                "solution_ar":     p["solution_ar"],
                "phases_en":       json.dumps(p["phases_en"]),
                "phases_ar":       json.dumps(p["phases_ar"]),
                "deliverables_en": json.dumps(p["deliverables_en"]),
                "deliverables_ar": json.dumps(p["deliverables_ar"]),
                "ppt_filename":    p["ppt_filename"],
                "ppt_data":        p["ppt_data"],
                "industries":      json.dumps(p["industries"]),
            },
        )


def downgrade() -> None:
    pass
